/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface DocumentsReq
 */
export interface DocumentsReq {
    /**
     * 
     * @type {ObjectId}
     * @memberof DocumentsReq
     */
    _id?: ObjectId;
    /**
     * 
     * @type {string}
     * @memberof DocumentsReq
     */
    acadYear?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsReq
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsReq
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsReq
     */
    docType?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsReq
     */
    file?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsReq
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsReq
     */
    semester?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentsReq
     */
    smsStatus?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentsReq
     */
    subject?: string;
}
/**
 * 
 * @export
 * @interface DocumentsRes
 */
export interface DocumentsRes {
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    _id?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    acadYear?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    docType?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    file?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    semester?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentsRes
     */
    smsStatus?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentsRes
     */
    subject?: string;
}
/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    recipient?: string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    subject?: string;
}
/**
 * 
 * @export
 * @interface ObjectId
 */
export interface ObjectId {
    /**
     * 
     * @type {number}
     * @memberof ObjectId
     */
    timestamp?: number;
}
/**
 * 
 * @export
 * @interface OfficersReq
 */
export interface OfficersReq {
    /**
     * 
     * @type {ObjectId}
     * @memberof OfficersReq
     */
    _id?: ObjectId;
    /**
     * 
     * @type {string}
     * @memberof OfficersReq
     */
    accountType?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersReq
     */
    contactNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersReq
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersReq
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersReq
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersReq
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersReq
     */
    position?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OfficersReq
     */
    session?: boolean;
}
/**
 * 
 * @export
 * @interface OfficersRes
 */
export interface OfficersRes {
    /**
     * 
     * @type {string}
     * @memberof OfficersRes
     */
    _id?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersRes
     */
    accountType?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersRes
     */
    contactNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersRes
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersRes
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersRes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersRes
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficersRes
     */
    position?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OfficersRes
     */
    session?: boolean;
}
/**
 * 
 * @export
 * @interface RecipientsReq
 */
export interface RecipientsReq {
    /**
     * 
     * @type {ObjectId}
     * @memberof RecipientsReq
     */
    _id?: ObjectId;
    /**
     * 
     * @type {string}
     * @memberof RecipientsReq
     */
    contact?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsReq
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsReq
     */
    institution?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsReq
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsReq
     */
    status?: string;
}
/**
 * 
 * @export
 * @interface RecipientsRes
 */
export interface RecipientsRes {
    /**
     * 
     * @type {string}
     * @memberof RecipientsRes
     */
    _id?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsRes
     */
    contact?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsRes
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsRes
     */
    institution?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsRes
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipientsRes
     */
    status?: string;
}
/**
 * 
 * @export
 * @interface Resource
 */
export interface Resource {
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    description?: string;
    /**
     * 
     * @type {any}
     * @memberof Resource
     */
    file?: any;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    filename?: string;
    /**
     * 
     * @type {object}
     * @memberof Resource
     */
    inputStream?: object;
    /**
     * 
     * @type {boolean}
     * @memberof Resource
     */
    open?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Resource
     */
    readable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    uri?: string;
    /**
     * 
     * @type {string}
     * @memberof Resource
     */
    url?: string;
}
/**
 * 
 * @export
 * @interface ResponseMessage
 */
export interface ResponseMessage {
    /**
     * 
     * @type {string}
     * @memberof ResponseMessage
     */
    message?: string;
}
/**
 * 
 * @export
 * @interface SMSs
 */
export interface SMSs {
    /**
     * 
     * @type {string}
     * @memberof SMSs
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SMSs
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof SMSs
     */
    subject?: string;
}
/**
 * 
 * @export
 * @interface UploadFileResponse
 */
export interface UploadFileResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadFileResponse
     */
    fileDownloadUri?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileResponse
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFileResponse
     */
    fileType?: string;
    /**
     * 
     * @type {number}
     * @memberof UploadFileResponse
     */
    size?: number;
}

/**
 * DocumentControllerApi - axios parameter creator
 * @export
 */
export const DocumentControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Insert some documents
         * @param {DocumentsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addDocument: async (model: DocumentsReq, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'model' is not null or undefined
            assertParamExists('addDocument', 'model', model)
            const localVarPath = `/sms-api/document/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(model, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUsingDELETE: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteUsingDELETE', 'id', id)
            const localVarPath = `/sms-api/document/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get document by id
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocument: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getDocument', 'id', id)
            const localVarPath = `/sms-api/document/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get get all documents
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocuments: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/sms-api/document/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update this document
         * @param {string} id id
         * @param {DocumentsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDocument: async (id: string, model: DocumentsReq, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateDocument', 'id', id)
            // verify required parameter 'model' is not null or undefined
            assertParamExists('updateDocument', 'model', model)
            const localVarPath = `/sms-api/document/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(model, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload some documents
         * @param {string} id id
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadDocument: async (id: string, file?: any, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('uploadDocument', 'id', id)
            const localVarPath = `/sms-api/document/upload/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DocumentControllerApi - functional programming interface
 * @export
 */
export const DocumentControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DocumentControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Insert some documents
         * @param {DocumentsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addDocument(model: DocumentsReq, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentsRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addDocument(model, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUsingDELETE(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUsingDELETE(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get document by id
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDocument(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentsRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDocument(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get get all documents
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDocuments(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DocumentsRes>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDocuments(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update this document
         * @param {string} id id
         * @param {DocumentsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDocument(id: string, model: DocumentsReq, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentsRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDocument(id, model, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Upload some documents
         * @param {string} id id
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadDocument(id: string, file?: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadDocument(id, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DocumentControllerApi - factory interface
 * @export
 */
export const DocumentControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DocumentControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Insert some documents
         * @param {DocumentsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addDocument(model: DocumentsReq, options?: any): AxiosPromise<DocumentsRes> {
            return localVarFp.addDocument(model, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUsingDELETE(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteUsingDELETE(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get document by id
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocument(id: string, options?: any): AxiosPromise<DocumentsRes> {
            return localVarFp.getDocument(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get get all documents
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocuments(options?: any): AxiosPromise<Array<DocumentsRes>> {
            return localVarFp.getDocuments(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update this document
         * @param {string} id id
         * @param {DocumentsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDocument(id: string, model: DocumentsReq, options?: any): AxiosPromise<DocumentsRes> {
            return localVarFp.updateDocument(id, model, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload some documents
         * @param {string} id id
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadDocument(id: string, file?: any, options?: any): AxiosPromise<ResponseMessage> {
            return localVarFp.uploadDocument(id, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DocumentControllerApi - object-oriented interface
 * @export
 * @class DocumentControllerApi
 * @extends {BaseAPI}
 */
export class DocumentControllerApi extends BaseAPI {
    /**
     * 
     * @summary Insert some documents
     * @param {DocumentsReq} model model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentControllerApi
     */
    public addDocument(model: DocumentsReq, options?: any) {
        return DocumentControllerApiFp(this.configuration).addDocument(model, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete
     * @param {string} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentControllerApi
     */
    public deleteUsingDELETE(id: string, options?: any) {
        return DocumentControllerApiFp(this.configuration).deleteUsingDELETE(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get document by id
     * @param {string} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentControllerApi
     */
    public getDocument(id: string, options?: any) {
        return DocumentControllerApiFp(this.configuration).getDocument(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get get all documents
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentControllerApi
     */
    public getDocuments(options?: any) {
        return DocumentControllerApiFp(this.configuration).getDocuments(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update this document
     * @param {string} id id
     * @param {DocumentsReq} model model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentControllerApi
     */
    public updateDocument(id: string, model: DocumentsReq, options?: any) {
        return DocumentControllerApiFp(this.configuration).updateDocument(id, model, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload some documents
     * @param {string} id id
     * @param {any} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentControllerApi
     */
    public uploadDocument(id: string, file?: any, options?: any) {
        return DocumentControllerApiFp(this.configuration).uploadDocument(id, file, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * FileControllerApi - axios parameter creator
 * @export
 */
export const FileControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Download file by file name
         * @param {string} fileName fileName
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadFile: async (fileName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileName' is not null or undefined
            assertParamExists('downloadFile', 'fileName', fileName)
            const localVarPath = `/sms-api/file/downloadFile/{fileName}`
                .replace(`{${"fileName"}}`, encodeURIComponent(String(fileName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload one file
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile: async (file?: any, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/sms-api/file/uploadFile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FileControllerApi - functional programming interface
 * @export
 */
export const FileControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FileControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Download file by file name
         * @param {string} fileName fileName
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadFile(fileName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resource>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadFile(fileName, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Upload one file
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFile(file?: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UploadFileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFile(file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FileControllerApi - factory interface
 * @export
 */
export const FileControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FileControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Download file by file name
         * @param {string} fileName fileName
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadFile(fileName: string, options?: any): AxiosPromise<Resource> {
            return localVarFp.downloadFile(fileName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload one file
         * @param {any} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile(file?: any, options?: any): AxiosPromise<UploadFileResponse> {
            return localVarFp.uploadFile(file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FileControllerApi - object-oriented interface
 * @export
 * @class FileControllerApi
 * @extends {BaseAPI}
 */
export class FileControllerApi extends BaseAPI {
    /**
     * 
     * @summary Download file by file name
     * @param {string} fileName fileName
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileControllerApi
     */
    public downloadFile(fileName: string, options?: any) {
        return FileControllerApiFp(this.configuration).downloadFile(fileName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload one file
     * @param {any} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileControllerApi
     */
    public uploadFile(file?: any, options?: any) {
        return FileControllerApiFp(this.configuration).uploadFile(file, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * MessageControllerApi - axios parameter creator
 * @export
 */
export const MessageControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Insert some message
         * @param {Message} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMessage: async (model: Message, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'model' is not null or undefined
            assertParamExists('addMessage', 'model', model)
            const localVarPath = `/sms-api/message/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(model, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get get all messages
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessages: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/sms-api/message/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessageControllerApi - functional programming interface
 * @export
 */
export const MessageControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessageControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Insert some message
         * @param {Message} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addMessage(model: Message, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Message>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addMessage(model, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get get all messages
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessages(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Message>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessages(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MessageControllerApi - factory interface
 * @export
 */
export const MessageControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessageControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Insert some message
         * @param {Message} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addMessage(model: Message, options?: any): AxiosPromise<Message> {
            return localVarFp.addMessage(model, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get get all messages
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessages(options?: any): AxiosPromise<Array<Message>> {
            return localVarFp.getMessages(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MessageControllerApi - object-oriented interface
 * @export
 * @class MessageControllerApi
 * @extends {BaseAPI}
 */
export class MessageControllerApi extends BaseAPI {
    /**
     * 
     * @summary Insert some message
     * @param {Message} model model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessageControllerApi
     */
    public addMessage(model: Message, options?: any) {
        return MessageControllerApiFp(this.configuration).addMessage(model, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get get all messages
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessageControllerApi
     */
    public getMessages(options?: any) {
        return MessageControllerApiFp(this.configuration).getMessages(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * OfficerControllerApi - axios parameter creator
 * @export
 */
export const OfficerControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Insert some officer
         * @param {OfficersReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAccount: async (model: OfficersReq, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'model' is not null or undefined
            assertParamExists('addAccount', 'model', model)
            const localVarPath = `/sms-api/officer/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(model, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete this officer
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOfficer: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteOfficer', 'id', id)
            const localVarPath = `/sms-api/officer/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get officer by id
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOfficer: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getOfficer', 'id', id)
            const localVarPath = `/sms-api/officer/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get get all officers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOfficers: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/sms-api/officer/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update this officer
         * @param {string} id id
         * @param {OfficersReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOfficer: async (id: string, model: OfficersReq, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateOfficer', 'id', id)
            // verify required parameter 'model' is not null or undefined
            assertParamExists('updateOfficer', 'model', model)
            const localVarPath = `/sms-api/officer/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(model, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OfficerControllerApi - functional programming interface
 * @export
 */
export const OfficerControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OfficerControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Insert some officer
         * @param {OfficersReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addAccount(model: OfficersReq, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfficersRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addAccount(model, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete this officer
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOfficer(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOfficer(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get officer by id
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOfficer(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfficersRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOfficer(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get get all officers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOfficers(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OfficersRes>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOfficers(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update this officer
         * @param {string} id id
         * @param {OfficersReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOfficer(id: string, model: OfficersReq, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OfficersRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOfficer(id, model, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OfficerControllerApi - factory interface
 * @export
 */
export const OfficerControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OfficerControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Insert some officer
         * @param {OfficersReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAccount(model: OfficersReq, options?: any): AxiosPromise<OfficersRes> {
            return localVarFp.addAccount(model, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete this officer
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOfficer(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteOfficer(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get officer by id
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOfficer(id: string, options?: any): AxiosPromise<OfficersRes> {
            return localVarFp.getOfficer(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get get all officers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOfficers(options?: any): AxiosPromise<Array<OfficersRes>> {
            return localVarFp.getOfficers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update this officer
         * @param {string} id id
         * @param {OfficersReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOfficer(id: string, model: OfficersReq, options?: any): AxiosPromise<OfficersRes> {
            return localVarFp.updateOfficer(id, model, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OfficerControllerApi - object-oriented interface
 * @export
 * @class OfficerControllerApi
 * @extends {BaseAPI}
 */
export class OfficerControllerApi extends BaseAPI {
    /**
     * 
     * @summary Insert some officer
     * @param {OfficersReq} model model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficerControllerApi
     */
    public addAccount(model: OfficersReq, options?: any) {
        return OfficerControllerApiFp(this.configuration).addAccount(model, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete this officer
     * @param {string} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficerControllerApi
     */
    public deleteOfficer(id: string, options?: any) {
        return OfficerControllerApiFp(this.configuration).deleteOfficer(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get officer by id
     * @param {string} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficerControllerApi
     */
    public getOfficer(id: string, options?: any) {
        return OfficerControllerApiFp(this.configuration).getOfficer(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get get all officers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficerControllerApi
     */
    public getOfficers(options?: any) {
        return OfficerControllerApiFp(this.configuration).getOfficers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update this officer
     * @param {string} id id
     * @param {OfficersReq} model model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficerControllerApi
     */
    public updateOfficer(id: string, model: OfficersReq, options?: any) {
        return OfficerControllerApiFp(this.configuration).updateOfficer(id, model, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * RecipientControllerApi - axios parameter creator
 * @export
 */
export const RecipientControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Insert some recipients
         * @param {Array<RecipientsReq>} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addRecipients: async (model: Array<RecipientsReq>, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'model' is not null or undefined
            assertParamExists('addRecipients', 'model', model)
            const localVarPath = `/sms-api/recipient/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(model, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete all recipient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRecipients: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/sms-api/recipient/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUsingDELETE1: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteUsingDELETE1', 'id', id)
            const localVarPath = `/sms-api/recipient/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GetById
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByIdUsingGET: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getByIdUsingGET', 'id', id)
            const localVarPath = `/sms-api/recipient/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get get all recipients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecipients: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/sms-api/recipient/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update
         * @param {string} id id
         * @param {RecipientsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUsingPUT: async (id: string, model: RecipientsReq, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateUsingPUT', 'id', id)
            // verify required parameter 'model' is not null or undefined
            assertParamExists('updateUsingPUT', 'model', model)
            const localVarPath = `/sms-api/recipient/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(model, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecipientControllerApi - functional programming interface
 * @export
 */
export const RecipientControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecipientControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Insert some recipients
         * @param {Array<RecipientsReq>} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addRecipients(model: Array<RecipientsReq>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RecipientsRes>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addRecipients(model, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete all recipient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRecipients(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRecipients(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUsingDELETE1(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUsingDELETE1(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary GetById
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByIdUsingGET(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipientsRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByIdUsingGET(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get get all recipients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecipients(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RecipientsRes>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecipients(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update
         * @param {string} id id
         * @param {RecipientsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUsingPUT(id: string, model: RecipientsReq, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecipientsRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUsingPUT(id, model, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RecipientControllerApi - factory interface
 * @export
 */
export const RecipientControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecipientControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Insert some recipients
         * @param {Array<RecipientsReq>} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addRecipients(model: Array<RecipientsReq>, options?: any): AxiosPromise<Array<RecipientsRes>> {
            return localVarFp.addRecipients(model, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete all recipient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRecipients(options?: any): AxiosPromise<void> {
            return localVarFp.deleteRecipients(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUsingDELETE1(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteUsingDELETE1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GetById
         * @param {string} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByIdUsingGET(id: string, options?: any): AxiosPromise<RecipientsRes> {
            return localVarFp.getByIdUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get get all recipients
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecipients(options?: any): AxiosPromise<Array<RecipientsRes>> {
            return localVarFp.getRecipients(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update
         * @param {string} id id
         * @param {RecipientsReq} model model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUsingPUT(id: string, model: RecipientsReq, options?: any): AxiosPromise<RecipientsRes> {
            return localVarFp.updateUsingPUT(id, model, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecipientControllerApi - object-oriented interface
 * @export
 * @class RecipientControllerApi
 * @extends {BaseAPI}
 */
export class RecipientControllerApi extends BaseAPI {
    /**
     * 
     * @summary Insert some recipients
     * @param {Array<RecipientsReq>} model model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientControllerApi
     */
    public addRecipients(model: Array<RecipientsReq>, options?: any) {
        return RecipientControllerApiFp(this.configuration).addRecipients(model, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete all recipient
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientControllerApi
     */
    public deleteRecipients(options?: any) {
        return RecipientControllerApiFp(this.configuration).deleteRecipients(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete
     * @param {string} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientControllerApi
     */
    public deleteUsingDELETE1(id: string, options?: any) {
        return RecipientControllerApiFp(this.configuration).deleteUsingDELETE1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GetById
     * @param {string} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientControllerApi
     */
    public getByIdUsingGET(id: string, options?: any) {
        return RecipientControllerApiFp(this.configuration).getByIdUsingGET(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get get all recipients
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientControllerApi
     */
    public getRecipients(options?: any) {
        return RecipientControllerApiFp(this.configuration).getRecipients(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update
     * @param {string} id id
     * @param {RecipientsReq} model model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipientControllerApi
     */
    public updateUsingPUT(id: string, model: RecipientsReq, options?: any) {
        return RecipientControllerApiFp(this.configuration).updateUsingPUT(id, model, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * SmsControllerApi - axios parameter creator
 * @export
 */
export const SmsControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Send some sms
         * @param {SMSs} smsRequest smsRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendSms: async (smsRequest: SMSs, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'smsRequest' is not null or undefined
            assertParamExists('sendSms', 'smsRequest', smsRequest)
            const localVarPath = `/sms-api/message`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(smsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SmsControllerApi - functional programming interface
 * @export
 */
export const SmsControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SmsControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Send some sms
         * @param {SMSs} smsRequest smsRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendSms(smsRequest: SMSs, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendSms(smsRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SmsControllerApi - factory interface
 * @export
 */
export const SmsControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SmsControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Send some sms
         * @param {SMSs} smsRequest smsRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendSms(smsRequest: SMSs, options?: any): AxiosPromise<void> {
            return localVarFp.sendSms(smsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SmsControllerApi - object-oriented interface
 * @export
 * @class SmsControllerApi
 * @extends {BaseAPI}
 */
export class SmsControllerApi extends BaseAPI {
    /**
     * 
     * @summary Send some sms
     * @param {SMSs} smsRequest smsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SmsControllerApi
     */
    public sendSms(smsRequest: SMSs, options?: any) {
        return SmsControllerApiFp(this.configuration).sendSms(smsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


